name: Build for Dreamcast (Target)
on: [push]
jobs:
  build-target:
    name: Build dcload-ip ELF/CDI
    runs-on: ubuntu-latest
    env:
      MKDCDISC_PATH: /tmp/mkdcdisc
      UPLOAD_DIR: /tmp/upload
      DCLOAD_AUTHOR: 
      DCLOAD_BRANCH: dcloadip-$GITHUB_REF_NAME-$GITHUB_SHA
      DCLOAD_SHA: 

      BUILD_DIR: builddir
      SH4_CROSS_FILE: sh4-kos-gcc.txt
    steps:
      - name: Install mkdcdisc      
        run: |
            sudo apt-get update
            sudo apt-get install meson git build-essential libisofs-dev
            git clone https://gitlab.com/cepawiel/mkdcdisc $MKDCDISC_PATH
            cd $MKDCDISC_PATH
            git checkout scramble
            meson setup builddir
            meson compile -C builddir
            
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build ELF
        run: |
            mkdir $UPLOAD_DIR
            docker run \
              --rm \
              -v $(pwd):/src \
              einsteinx2/dcdev-gcc-toolchain:latest \
             "apk add git binutils meson && \
              cd target && \
              meson setup -Drepo="$GITHUB_REPOSITORY" -Dbranch="$GITHUB_REF_NAME" -Dsha="$GITHUB_SHA" --cross-file sh4-kos-gcc.txt $BUILD_DIR && \
              meson compile -C $BUILD_DIR --verbose"
            readelf --sections target/$BUILD_DIR/dcload/dcloadip.elf
            cp target/$BUILD_DIR/loader/loader.elf $UPLOAD_DIR/
            
      - name: Build Padded CDI
        run: $MKDCDISC_PATH/builddir/mkdcdisc
                --verbosity 3
                --elf target/builddir/loader/loader.elf
                --name "dcloadip"
                --author "$GITHUB_REPOSITORY_OWNER"
                --output $UPLOAD_DIR/dcload-ip-padded.cdi

      - name: Build CDI
        run: $MKDCDISC_PATH/builddir/mkdcdisc
                --verbosity 3
                --elf target/builddir/loader/loader.elf
                --no-padding
                --name "dcloadip"
                --author "$GITHUB_REPOSITORY_OWNER"
                --output $UPLOAD_DIR/dcload-ip.cdi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dcloadip
          path: /tmp/upload/*

  build-host:
    name: Build Host Tool and Test
    needs: build-target
    runs-on: [self-hosted, dreamcast-bba]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build Tool     
        run: |
            sudo apt-get update
            sudo apt-get install -y meson build-essential libelf-dev pkg-config
            sudo apt-get remove -y gcc-9 g++-9
            sudo apt-get install -y gcc-12 g++-12
            cd host
            ./build.sh
            chmod +x builddir/tests/run_tests
        
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: dcloadip
          path: /tmp/dcload

      - name: Power on Dreamcast
        run: |
            curl -X POST http://172.16.50.116/switch/dev_dreamcast_power/turn_on
            sleep 30

      - name: Run dcload Tests
        run: |
            ./host/builddir/tests/run_tests

      - name: Power Off Dreamcast
        if: always()
        run: curl -X POST http://172.16.50.116/switch/dev_dreamcast_power/turn_off

      # - name: Upload Test Logs
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dctool
      #     path: host-src/tool/dc-tool-ip
